version: '3.5'

services:
  cot-gateway:
    image: vipr-mvp
    build: .
    container_name: vipr-cot-gw
    ports:
      - 8087:8087
    volumes:
      - ./:/vipr
    command: "python -u /vipr/CoT_gateway.py"
    
  adsb-emulator:
    image: vipr-mvp
    build: .
    container_name: vipr-adsb-em
    ports:
      - 30002:30002
    volumes:
      - ./:/vipr/
    command: "python -u /vipr/adsb_emulator.py"

  adsbcot:
    image: vipr-mvp
    build: .
    container_name: vipr-adsbcot
    depends_on:
      - cot-gateway
      - adsb-emulator
    command: "adsbcot -U tcp:vipr-cot-gw:8087 -D tcp+raw:vipr-adsb-em:30002"

  cotvalid:
    image: vipr-mvp
    build: .
    container_name: vipr-validate
    depends_on:
      - cot-gateway
      - adsb-emulator
      - adsbcot
    volumes:
      - ./:/vipr/
    command: "python -u /vipr/CoT_validate.py"
