version: '3.5'

services:
  orchestrator:
    image: vipr-orchestrator:latest
    build: .
    volumes:
      - ./:/vipr
      - /var/run/docker.sock:/var/run/docker.sock
    command: 'python -u /vipr/orchestrator.py -r "https://github.com/bryanjonas/adsbcot"'